import React from 'react';
import { useHelloQuery } from './generated/graphql';
import './App.css';

const App: React.FC = () => {
	// write a query in /graphql
	// yarn gen -> creates a typesafe custom hook in /generated/graphql.tsx
	// use that hook to access { data, loading } = use[NAME]Query // [NAME] is autogenerated from query in /graphql files

	const { data, loading } = useHelloQuery();

	if (loading || !data) {
		return <div>loading ...</div>;
	} else {
		return <div>{data.hello}</div>;
	}
};

export default App;
